import os
import sys

# Add the parent directory to sys.path to allow importing from app
sys.path.append(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))

from app import create_app, db
from sqlalchemy.schema import CreateTable
from sqlalchemy.dialects import postgresql

def generate_sql_script():
    """
    Generate PostgreSQL DDL script from SQLAlchemy models
    """
    app = create_app('development')
    
    with app.app_context():
        print("-- PostgreSQL DDL Script generated by scripts/generate_sql.py")
        print(f"-- Generated at: {os.popen('date').read().strip()}")
        print("\n-- Disable foreign key constraints temporarily")
        print("SET session_replication_role = 'replica';")
        print("GO\n")

        # Get all tables from metadata
        metadata = db.metadata
        
        # Sort tables to respect foreign key dependencies (optional, but good for readability)
        sorted_tables = metadata.sorted_tables
        
        for table in sorted_tables:
            # Generate CREATE TABLE statement using PostgreSQL dialect
            create_table_sql = CreateTable(table).compile(dialect=postgresql.dialect())
            print(f"-- Table: {table.name}")
            print(str(create_table_sql).strip() + ";")
            print("GO\n")
            
        print("-- Re-enable foreign key constraints")
        print("SET session_replication_role = 'origin';")
        print("GO")

if __name__ == "__main__":
    generate_sql_script()
